# Week 4 and 5 - Assignment from the classes 02/26 and 03/06

In [1]:
import numpy as np
import pandas as pd

# 1. Create a 2D array and print the dim and shape

In [2]:
arr1 = np.array([10,20,50,30,40])
print('Dimention of numpy array : ', arr1.ndim)
print('Shape of numpy array : ', arr1.shape)

Dimention of numpy array :  1
Shape of numpy array :  (5,)


# 2. Create an array of 20 numbers using arange function and slice the values between 10 to 15


In [3]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
slice1 = slice(10,15,1)

In [5]:
arr22 = arr2[slice1]
arr22

array([10, 11, 12, 13, 14])

# 3. Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using
### a. Addition b. Subtraction c. Multiplication d. Division

In [6]:
a1 = np.array([[1,2,3,4,5],
               [6,7,8,9,0],
               [11,22,33,44,55],
               [66,77,88,99,10],
               [10,20,30,40,50],
               [8,5,2,3,9],
               [2,3,4,5,6]])

a2 = np.array([[10,20,30,40,50],
               [60,70,80,90,10],
               [1,2,3,4,5],
               [6,7,8,9,0],
               [10,20,30,40,50],
               [1,5,2,3,4],
               [2,3,8,5,1]])

In [7]:
print("Addition of two arrays : ")
print(a1+a2)
print('\n')
print('addition of two matrices using add function')
print(np.add(a1,a2))

Addition of two arrays : 
[[ 11  22  33  44  55]
 [ 66  77  88  99  10]
 [ 12  24  36  48  60]
 [ 72  84  96 108  10]
 [ 20  40  60  80 100]
 [  9  10   4   6  13]
 [  4   6  12  10   7]]


addition of two matrices using add function
[[ 11  22  33  44  55]
 [ 66  77  88  99  10]
 [ 12  24  36  48  60]
 [ 72  84  96 108  10]
 [ 20  40  60  80 100]
 [  9  10   4   6  13]
 [  4   6  12  10   7]]


In [8]:
print("Subtraction of two arrays : ")
print(a1-a2)
print('\n')
print('subtraction of two matrices  using subtract function')
print(np.subtract(a1,a2))

Subtraction of two arrays : 
[[ -9 -18 -27 -36 -45]
 [-54 -63 -72 -81 -10]
 [ 10  20  30  40  50]
 [ 60  70  80  90  10]
 [  0   0   0   0   0]
 [  7   0   0   0   5]
 [  0   0  -4   0   5]]


subtraction of two matrices  using subtract function
[[ -9 -18 -27 -36 -45]
 [-54 -63 -72 -81 -10]
 [ 10  20  30  40  50]
 [ 60  70  80  90  10]
 [  0   0   0   0   0]
 [  7   0   0   0   5]
 [  0   0  -4   0   5]]


In [9]:
print("Multiplication of two arrays : ")
print(a1*a2)
print('\n')
print('multiply of two matrices  using multiply function')
print(np.multiply(a1,a2))

Multiplication of two arrays : 
[[  10   40   90  160  250]
 [ 360  490  640  810    0]
 [  11   44   99  176  275]
 [ 396  539  704  891    0]
 [ 100  400  900 1600 2500]
 [   8   25    4    9   36]
 [   4    9   32   25    6]]


multiply of two matrices  using multiply function
[[  10   40   90  160  250]
 [ 360  490  640  810    0]
 [  11   44   99  176  275]
 [ 396  539  704  891    0]
 [ 100  400  900 1600 2500]
 [   8   25    4    9   36]
 [   4    9   32   25    6]]


In [10]:
print("Division of two arrays : ")
print(a1/a2)
print('\n')
print('division of two matrices using divide function')
print(np.divide(a1,a2))


Division of two arrays : 
[[ 0.1   0.1   0.1   0.1   0.1 ]
 [ 0.1   0.1   0.1   0.1   0.  ]
 [11.   11.   11.   11.   11.  ]
 [11.   11.   11.   11.     inf]
 [ 1.    1.    1.    1.    1.  ]
 [ 8.    1.    1.    1.    2.25]
 [ 1.    1.    0.5   1.    6.  ]]


division of two matrices using divide function
[[ 0.1   0.1   0.1   0.1   0.1 ]
 [ 0.1   0.1   0.1   0.1   0.  ]
 [11.   11.   11.   11.   11.  ]
 [11.   11.   11.   11.     inf]
 [ 1.    1.    1.    1.    1.  ]
 [ 8.    1.    1.    1.    2.25]
 [ 1.    1.    0.5   1.    6.  ]]


C:\Users\maham\AppData\Local\Temp/ipykernel_2696/988076298.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(a1/a2)
C:\Users\maham\AppData\Local\Temp/ipykernel_2696/988076298.py:5: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(a1,a2))


# 4. Create 2 incompatible arrays for broadcast and print out the error


In [11]:
np.array([[10,20,30],[1,2,3,4,5]])

C:\Users\maham\AppData\Local\Temp/ipykernel_2696/951430913.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[10,20,30],[1,2,3,4,5]])


array([list([10, 20, 30]), list([1, 2, 3, 4, 5])], dtype=object)

# 5. Create two arrays of any dimension and perform vstack and hstack


In [12]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[10,20,30],[40,50,60]])

In [13]:
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [14]:
np.hstack((a1,a2))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

# 6. Append two arrays using axis = 0 and axis = 1


In [15]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[10,20,30],[40,50,60]])

In [16]:
np.append(a1,a2,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [17]:
np.append(a1,a2,axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

# 7. Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation


In [23]:
list1 = [[1,'Mahammad',24,'M'],
         [2,'Rafi',32,'M'],
         [3,'Mango',33,'F'],
         [4,'Apple',44,'M'],
         [5,'Ameen',36,'F'],
         [3,'Manchu',53,'F'],
         [11,'Hello',24,'F'],
         [12,'Surya',32,'M'],
         [13,'Patanjali',63,'M']]

In [24]:
df = pd.DataFrame(list1, columns =['S.No', 'Name', 'Age', 'Gender'] )

In [25]:
df

S.No       Name  Age Gender
0     1   Mahammad   24      M
1     2       Rafi   32      M
2     3      Mango   33      F
3     4      Apple   44      M
4     5      Ameen   36      F
5     3     Manchu   53      F
6    11      Hello   24      F
7    12      Surya   32      M
8    13  Patanjali   63      M

# 8. Create a dataframe of 4 X 8 dimension using a dictionary


In [26]:
dict2 = {'state': ['Tamilnadu','telangana','karanataka','goa'], 
         'city': ['Chennai','Hyderabad','Banglore','panaji'], 
         'const': [10,20,30,40], 
         'No_of_school': [100,200,300,105],
         'No_of_library': [3,2,4,8],
         'No_of_colleges': [33, 22, 10, 3],
         'population': [80000000, 50000000, 60000000, 10000000],
         'male_pop':   [40000000, 20000000, 35000000, 7000000],
         'female_pop': [35000000, 30000000, 25000000, 3000000]}

In [27]:
df1 = pd.DataFrame(dict2)
df1

state       city  const  No_of_school  No_of_library  No_of_colleges  \
0   Tamilnadu    Chennai     10           100              3              33   
1   telangana  Hyderabad     20           200              2              22   
2  karanataka   Banglore     30           300              4              10   
3         goa     panaji     40           105              8               3   

   population  male_pop  female_pop  
0    80000000  40000000    35000000  
1    50000000  20000000    30000000  
2    60000000  35000000    25000000  
3    10000000   7000000     3000000

In [28]:
df1['tot_male_female'] = df1['male_pop'] + df1['female_pop']
df1

state       city  const  No_of_school  No_of_library  No_of_colleges  \
0   Tamilnadu    Chennai     10           100              3              33   
1   telangana  Hyderabad     20           200              2              22   
2  karanataka   Banglore     30           300              4              10   
3         goa     panaji     40           105              8               3   

   population  male_pop  female_pop  tot_male_female  
0    80000000  40000000    35000000         75000000  
1    50000000  20000000    30000000         50000000  
2    60000000  35000000    25000000         60000000  
3    10000000   7000000     3000000         10000000

# 9. Use loc and ilocto subset the data for the above dataframe


In [30]:
df1.iloc[1:2,1:4]

city  const  No_of_school
1  Hyderabad     20           200

In [31]:
df1.loc[1:2,['city', 'population']]

city  population
1  Hyderabad    50000000
2   Banglore    60000000

In [32]:
df1.loc[1:2]

state       city  const  No_of_school  No_of_library  No_of_colleges  \
1   telangana  Hyderabad     20           200              2              22   
2  karanataka   Banglore     30           300              4              10   

   population  male_pop  female_pop  tot_male_female  
1    50000000  20000000    30000000         50000000  
2    60000000  35000000    25000000         60000000

# 10. How to check the total number of not null values in a column?


In [33]:
df1['city'].notnull().sum()

4

In [34]:
df1['city'].isnull().sum()

0

# 11. Create a dataframe with missing values and fill them all with 100


In [35]:
df2 = df1.reindex([1,2,3,4,5])

In [36]:
df2

state       city  const  No_of_school  No_of_library  No_of_colleges  \
1   telangana  Hyderabad   20.0         200.0            2.0            22.0   
2  karanataka   Banglore   30.0         300.0            4.0            10.0   
3         goa     panaji   40.0         105.0            8.0             3.0   
4         NaN        NaN    NaN           NaN            NaN             NaN   
5         NaN        NaN    NaN           NaN            NaN             NaN   

   population    male_pop  female_pop  tot_male_female  
1  50000000.0  20000000.0  30000000.0       50000000.0  
2  60000000.0  35000000.0  25000000.0       60000000.0  
3  10000000.0   7000000.0   3000000.0       10000000.0  
4         NaN         NaN         NaN              NaN  
5         NaN         NaN         NaN              NaN

In [37]:
df2.fillna(100)

state       city  const  No_of_school  No_of_library  No_of_colleges  \
1   telangana  Hyderabad   20.0         200.0            2.0            22.0   
2  karanataka   Banglore   30.0         300.0            4.0            10.0   
3         goa     panaji   40.0         105.0            8.0             3.0   
4         100        100  100.0         100.0          100.0           100.0   
5         100        100  100.0         100.0          100.0           100.0   

   population    male_pop  female_pop  tot_male_female  
1  50000000.0  20000000.0  30000000.0       50000000.0  
2  60000000.0  35000000.0  25000000.0       60000000.0  
3  10000000.0   7000000.0   3000000.0       10000000.0  
4       100.0       100.0       100.0            100.0  
5       100.0       100.0       100.0            100.0

# 12. Create a dataframe with missing values and drop the null records


In [39]:
df3 = df1.reindex([1,2,3,4,5])
df3

state       city  const  No_of_school  No_of_library  No_of_colleges  \
1   telangana  Hyderabad   20.0         200.0            2.0            22.0   
2  karanataka   Banglore   30.0         300.0            4.0            10.0   
3         goa     panaji   40.0         105.0            8.0             3.0   
4         NaN        NaN    NaN           NaN            NaN             NaN   
5         NaN        NaN    NaN           NaN            NaN             NaN   

   population    male_pop  female_pop  tot_male_female  
1  50000000.0  20000000.0  30000000.0       50000000.0  
2  60000000.0  35000000.0  25000000.0       60000000.0  
3  10000000.0   7000000.0   3000000.0       10000000.0  
4         NaN         NaN         NaN              NaN  
5         NaN         NaN         NaN              NaN

In [40]:
df3.dropna(inplace = True)
df3

state       city  const  No_of_school  No_of_library  No_of_colleges  \
1   telangana  Hyderabad   20.0         200.0            2.0            22.0   
2  karanataka   Banglore   30.0         300.0            4.0            10.0   
3         goa     panaji   40.0         105.0            8.0             3.0   

   population    male_pop  female_pop  tot_male_female  
1  50000000.0  20000000.0  30000000.0       50000000.0  
2  60000000.0  35000000.0  25000000.0       60000000.0  
3  10000000.0   7000000.0   3000000.0       10000000.0

# 13. Perform following aggregation task on below table
a. Get the average age group by Regrion

b. Get the sum of Age and Validation group by Hair color and then reset the index

c. Get the mean and the median of Age group by Region

In [41]:
list1 = [[25,'Black','Southwest',1],
         [30,'Black','Northwest',1],
         [45,'Red','Northeast',1],
         [35,'Blond','Southwest',0],
         [33,'Brown','Southwest',0],
         [33,'Brown','Southwest',0],
         [25,'Black','Southwest',0],
         [52,'Brown','Southeast',0],
         [21,'Blond','Southwest',1],
         [21,'Blond','Southwest',1],
         [48,'Black','Southwest',1],
         [22,'Black','Southwest',0],
         [27,'Brown','Northeast',0],
         [28,'Black','Southeast',1],
         [21,'Blond','Southeast',1],
         [51,'Black','Northwest',0],
         [23,'Brown','Southeast',1]
         ]

In [42]:
df = pd.DataFrame(list1, columns = ['Age', 'Hair Color', 'U.S. Region', 'Validation'])
df

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [43]:
df['Age'].mean()

31.764705882352942

In [44]:
df.groupby(['Hair Color'])['Age'].count()

Hair Color
Black    7
Blond    4
Brown    5
Red      1
Name: Age, dtype: int64

In [45]:
df1 = df.groupby(['Hair Color'])['Age'].sum().reset_index()
df1

Hair Color  Age
0      Black  229
1      Blond   98
2      Brown  168
3        Red   45

In [46]:
df2 = df.groupby(['U.S. Region'])['Age'].mean().reset_index()
df2

U.S. Region        Age
0   Northeast  36.000000
1   Northwest  40.500000
2   Southeast  31.000000
3   Southwest  29.222222

In [47]:
df3 = df.groupby(['U.S. Region'])['Age'].median().reset_index()
df3

U.S. Region   Age
0   Northeast  36.0
1   Northwest  40.5
2   Southeast  25.5
3   Southwest  25.0

# 14. Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [50]:
df

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [51]:
df_left = df.loc[0:10]
print(df1)

df_right = df.loc[10:]
print(df2)

  Hair Color  Age
0      Black  229
1      Blond   98
2      Brown  168
3        Red   45
  U.S. Region        Age
0   Northeast  36.000000
1   Northwest  40.500000
2   Southeast  31.000000
3   Southwest  29.222222


In [52]:
pd.merge(df_left, df_right, on = 'Age')

Age Hair Color_x U.S. Region_x  Validation_x Hair Color_y U.S. Region_y  \
0   21        Blond     Southwest             1        Blond     Southeast   
1   21        Blond     Southwest             1        Blond     Southeast   
2   48        Black     Southwest             1        Black     Southwest   

   Validation_y  
0             1  
1             1  
2             1

In [53]:
pd.merge(df_left, df_right, on = ['Age','Hair Color'])

Age Hair Color U.S. Region_x  Validation_x U.S. Region_y  Validation_y
0   21      Blond     Southwest             1     Southeast             1
1   21      Blond     Southwest             1     Southeast             1
2   48      Black     Southwest             1     Southwest             1

In [54]:
df_left.merge(df_right, on = 'Age', how = 'left')

Age Hair Color_x U.S. Region_x  Validation_x Hair Color_y U.S. Region_y  \
0    25        Black     Southwest             1          NaN           NaN   
1    30        Black     Northwest             1          NaN           NaN   
2    45          Red     Northeast             1          NaN           NaN   
3    35        Blond     Southwest             0          NaN           NaN   
4    33        Brown     Southwest             0          NaN           NaN   
5    33        Brown     Southwest             0          NaN           NaN   
6    25        Black     Southwest             0          NaN           NaN   
7    52        Brown     Southeast             0          NaN           NaN   
8    21        Blond     Southwest             1        Blond     Southeast   
9    21        Blond     Southwest             1        Blond     Southeast   
10   48        Black     Southwest             1        Black     Southwest   

    Validation_y  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
5            NaN  
6            NaN  
7            NaN  
8            1.0  
9            1.0  
10           1.0

In [55]:
df_left.merge(df_right, on = 'Age', how = 'right')

Age Hair Color_x U.S. Region_x  Validation_x Hair Color_y U.S. Region_y  \
0   48        Black     Southwest           1.0        Black     Southwest   
1   22          NaN           NaN           NaN        Black     Southwest   
2   27          NaN           NaN           NaN        Brown     Northeast   
3   28          NaN           NaN           NaN        Black     Southeast   
4   21        Blond     Southwest           1.0        Blond     Southeast   
5   21        Blond     Southwest           1.0        Blond     Southeast   
6   51          NaN           NaN           NaN        Black     Northwest   
7   23          NaN           NaN           NaN        Brown     Southeast   

   Validation_y  
0             1  
1             0  
2             0  
3             1  
4             1  
5             1  
6             0  
7             1

In [56]:
df_left.merge(df_right, on = 'Age', how = 'left').loc[:, ['Hair Color_x', 'Validation_x', 'Validation_y']]

Hair Color_x  Validation_x  Validation_y
0         Black             1           NaN
1         Black             1           NaN
2           Red             1           NaN
3         Blond             0           NaN
4         Brown             0           NaN
5         Brown             0           NaN
6         Black             0           NaN
7         Brown             0           NaN
8         Blond             1           1.0
9         Blond             1           1.0
10        Black             1           1.0

# 15. Split the below table and perform concat row wise and column wise


In [57]:
pd.concat([df_left, df_right], axis = 0)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [58]:
pd.concat([df_left, df_right], axis = 1)

Age Hair Color U.S. Region  Validation   Age Hair Color U.S. Region  \
0   25.0      Black   Southwest         1.0   NaN        NaN         NaN   
1   30.0      Black   Northwest         1.0   NaN        NaN         NaN   
2   45.0        Red   Northeast         1.0   NaN        NaN         NaN   
3   35.0      Blond   Southwest         0.0   NaN        NaN         NaN   
4   33.0      Brown   Southwest         0.0   NaN        NaN         NaN   
5   33.0      Brown   Southwest         0.0   NaN        NaN         NaN   
6   25.0      Black   Southwest         0.0   NaN        NaN         NaN   
7   52.0      Brown   Southeast         0.0   NaN        NaN         NaN   
8   21.0      Blond   Southwest         1.0   NaN        NaN         NaN   
9   21.0      Blond   Southwest         1.0   NaN        NaN         NaN   
10  48.0      Black   Southwest         1.0  48.0      Black   Southwest   
11   NaN        NaN         NaN         NaN  22.0      Black   Southwest   
12   NaN        NaN         NaN         NaN  27.0      Brown   Northeast   
13   NaN        NaN         NaN         NaN  28.0      Black   Southeast   
14   NaN        NaN         NaN         NaN  21.0      Blond   Southeast   
15   NaN        NaN         NaN         NaN  51.0      Black   Northwest   
16   NaN        NaN         NaN         NaN  23.0      Brown   Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          NaN  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0

In [59]:
pd.concat([df_left, df_right], ignore_index = True)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
11   48      Black   Southwest           1
12   22      Black   Southwest           0
13   27      Brown   Northeast           0
14   28      Black   Southeast           1
15   21      Blond   Southeast           1
16   51      Black   Northwest           0
17   23      Brown   Southeast           1

In [60]:
df_left.append(df_right)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [61]:
df_left.append(df_right, ignore_index = True)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
11   48      Black   Southwest           1
12   22      Black   Southwest           0
13   27      Brown   Northeast           0
14   28      Black   Southeast           1
15   21      Blond   Southeast           1
16   51      Black   Northwest           0
17   23      Brown   Southeast           1

In [62]:
df_temp = df_left.append(df_right)
df_temp

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    33      Brown   Southwest           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    21      Blond   Southwest           1
10   48      Black   Southwest           1
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [63]:
df_temp.reset_index()

index  Age Hair Color U.S. Region  Validation
0       0   25      Black   Southwest           1
1       1   30      Black   Northwest           1
2       2   45        Red   Northeast           1
3       3   35      Blond   Southwest           0
4       4   33      Brown   Southwest           0
5       5   33      Brown   Southwest           0
6       6   25      Black   Southwest           0
7       7   52      Brown   Southeast           0
8       8   21      Blond   Southwest           1
9       9   21      Blond   Southwest           1
10     10   48      Black   Southwest           1
11     10   48      Black   Southwest           1
12     11   22      Black   Southwest           0
13     12   27      Brown   Northeast           0
14     13   28      Black   Southeast           1
15     14   21      Blond   Southeast           1
16     15   51      Black   Northwest           0
17     16   23      Brown   Southeast           1