# Day-7 session - 26th February 2022 on python
1. Numpy

a. shape, ndim, reshape, default array

b. Create an array with existing data

c. Array from numerical ranges

d. Slicing

e. Integer Indexing

f. nan (null values concept)`

# Numpy and Pandas
Numpy(Numerical python) - it is for arrays, numeric calculations

Pandas is for a dataframes(table), calculation, performance is slow

# Numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [6]:
array1.ndim

1

In [7]:
array2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [8]:
array2.shape

(2, 5)

In [9]:
array2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [10]:
array3 = np.array([1,2,3], [4,5,6,7]) # arrays sequence should be in order

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [12]:
array3 = np.array([[1,2,3], [4,5,6]])

In [13]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array4 = np.array([[1, 'Rafi', 50.9], [2, 'Mango', 89.87], [3, 'Apple', 100.0]])

In [16]:
array4

array([['1', 'Rafi', '50.9'],
       ['2', 'Mango', '89.87'],
       ['3', 'Apple', '100.0']], dtype='<U32')

In [17]:
array4.shape

(3, 3)

In [18]:
array5 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]], dtype = float)

In [19]:
array5

array([[ 1.,  2.,  3.,  4.,  5.],
       [11., 22., 33., 44., 55.]])

In [20]:
array5.shape

(2, 5)

In [21]:
array_reshape = array5.reshape(5,2)

In [22]:
array_reshape

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5., 11.],
       [22., 33.],
       [44., 55.]])

In [23]:
array_reshape = array5.reshape(10,1)

In [24]:
array_reshape

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [11.],
       [22.],
       [33.],
       [44.],
       [55.]])

In [25]:
array_reshape = array5.reshape(1,10)

In [26]:
array_reshape

array([[ 1.,  2.,  3.,  4.,  5., 11., 22., 33., 44., 55.]])

In [27]:
array_zero = np.zeros(8)

In [28]:
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
array5.shape?

In [30]:
array6 = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]]]])

In [31]:
array6 

array([[[[1. , 2. , 3. , 4. , 5. ],
         [4. , 5. , 6. , 7. , 8. ],
         [1.2, 3.4, 5.6, 7.8, 9.1],
         [4. , 4. , 4. , 4. , 5. ]]]])

In [32]:
array6.shape   ## No use with this example having multiple dimensions in the same

(1, 1, 4, 5)

In [33]:
array7 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]])

In [34]:
array7.shape

(4, 5)

In [35]:
iter?

In [36]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])

In [37]:
array7 

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[1, 3, 5, 7, 9],
        [4, 4, 4, 4, 5]]])

In [38]:
len(array7)

2

In [39]:
array7.shape

(2, 2, 5)

In [40]:
array_zero = np.zeros(8)

In [41]:
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
array_ones = np.ones([3,3], dtype=int)

In [43]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Creating an array with existing data


In [44]:
x1 = ([3, 5], [5,4], [6,7])

In [45]:
n1 = ([[3, 5], [5,4], [6,7]], dtype = float)

SyntaxError: invalid syntax (Temp/ipykernel_15680/1213016252.py, line 1)

In [46]:
a1 = np.asarray(x1, dtype=float)  ## asarray() is a function

In [47]:
type(x1)

tuple

In [48]:
x1

([3, 5], [5, 4], [6, 7])

In [49]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

# Array from Numerical ranges


In [50]:
a1 = np.arange(0,20,3)

In [51]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [52]:
a1 = np.linspace(10,20,3)

In [53]:
a1

array([10., 15., 20.])

In [54]:
a1 = np.linspace(10,20,6)

In [55]:
a1

array([10., 12., 14., 16., 18., 20.])

In [56]:
a1 = np.linspace(10,20,5)

In [57]:
a1

array([10. , 12.5, 15. , 17.5, 20. ])

# Slicing

In [59]:
list1 = np.arange(10)

#list1

In [60]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
array1 = slice(2,9,2)

In [62]:
array1

slice(2, 9, 2)

In [63]:
list1[array1]

array([2, 4, 6, 8])

In [64]:
list2 = list1[array1]

In [65]:
list2

array([2, 4, 6, 8])

In [66]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array2 = slice(2,9)
list1[array2]

array([2, 3, 4, 5, 6, 7, 8])

In [68]:
list1 = np.arange(10)
array1 = list1[2: 9: 2]
list1[array1]

array([2, 4, 6, 8])

In [69]:
array1 = list1[2: 9]

In [70]:
array1

array([2, 3, 4, 5, 6, 7, 8])

In [71]:
len(array1)

7

In [72]:
array1.ndim

1

In [73]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])

In [74]:
array7 

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[1, 3, 5, 7, 9],
        [4, 4, 4, 4, 5]]])

In [75]:
len(array7[1][1])

5

In [76]:
array7.shape

(2, 2, 5)

In [77]:
array7.ndim

3

In [78]:
len(array7[0][1])

5

In [79]:
array7 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1,3,5,7,9],[4,4,4,4,5]])

In [80]:
len(array7)

4

In [81]:
len(array7[2])

5

In [82]:
array7.shape

(4, 5)

In [83]:
array7.ndim

2

In [84]:
array7= np.array([[[1,3,4,5],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]]])

In [85]:
array7

array([[[1, 3, 4, 5],
        [3, 4, 5, 6],
        [3, 4, 5, 6]],

       [[5, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]],

       [[5, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]]])

In [86]:
array7.ndim

3

In [87]:
array7.shape

(3, 3, 4)

# Integer indexing


In [88]:
a = np.array([[1,2],[3,4],[5,6]])
b = a[[0,1,2],[0,1,0]]

In [89]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
b

array([1, 4, 5])

In [91]:
a[1][0]

3

In [92]:
a1 = np.array([[1,2,3,4],[11,22,33,44],[111,222,333,444],[1111,2222,3333,4444]])

In [93]:
b1 = a1[1:,1:]

In [94]:
b1

array([[  22,   33,   44],
       [ 222,  333,  444],
       [2222, 3333, 4444]])

In [95]:
a1[1:][1:]   # don't use it

array([[ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [96]:
a1[1:4,1:3]

array([[  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [97]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [98]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
b1 = b[1:4, [1,2]]

In [100]:
b1

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [101]:
b1 = b[:4, :3]

In [102]:
b1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
a1 = np.array([[1,2,3,4],[11,22,33,44],[111,222,333,444],[1111,2222,3333,4444]])

In [104]:
a1

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [105]:
x = a1[1:5, [1,2,3]]

In [106]:
x

array([[  22,   33,   44],
       [ 222,  333,  444],
       [2222, 3333, 4444]])

In [107]:
a1[0:, [1,2,3]]

array([[   2,    3,    4],
       [  22,   33,   44],
       [ 222,  333,  444],
       [2222, 3333, 4444]])

In [108]:
a1[0:, [1,2]]

array([[   2,    3],
       [  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [109]:
a1[1:,[1,2]]

array([[  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [110]:
a1[[1,2,3],1:3]

array([[  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [111]:
a1

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [112]:
a1[a1<4]

array([1, 2, 3])

In [113]:
a1[a1>=4]

array([   4,   11,   22,   33,   44,  111,  222,  333,  444, 1111, 2222,
       3333, 4444])

# nan example - null values

In [114]:
a2 = np.array([1, 5, np.nan, 8, np.nan, 52, 65, np.nan])   # nan means a null value

In [115]:
a2

array([ 1.,  5., nan,  8., nan, 52., 65., nan])

In [116]:
a2[np.isnan(a2)]

array([nan, nan, nan])

In [117]:
a2[~np.isnan(a2)]

array([ 1.,  5.,  8., 52., 65.])

In [118]:
a1

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [119]:
a1[np.isnan(a1)]

array([], dtype=int32)

In [120]:
a1[2,3]

444

In [121]:
for a in a1:
    if a == 222:
        print(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()