In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer # from sklearn.preprocessing import Imputer (got error, so replaced with this and below line)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #(https://stackoverflow.com/questions/59439096/importerror-cannnot-import-name-imputer-from-sklearn-preprocessing)

In [12]:
import os
pwd = os.getcwd()
pwd

'C:\\Users\\maham\\Documents'

In [13]:
os.chdir(r'C:\Users\maham\Documents')

In [14]:
cancer_data = np.genfromtxt(fname ='Cancer.csv', delimiter= ',', dtype= float)

In [15]:
type(cancer_data)

numpy.ndarray

In [16]:
cancer_data

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

In [17]:
cancer_data[0]

array([1.000025e+06, 5.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 2.000000e+00, 1.000000e+00, 3.000000e+00,
       1.000000e+00, 1.000000e+00, 2.000000e+00])

In [18]:
print ("Dataset Lenght:: ", len(cancer_data))
print ("Dataset Shape:: ", cancer_data.shape)

Dataset Lenght::  699
Dataset Shape::  (699, 11)


In [19]:
cancer_data = np.delete(arr = cancer_data, obj= 0, axis = 1)

In [20]:
cancer_data

array([[ 5.,  1.,  1., ...,  1.,  1.,  2.],
       [ 5.,  4.,  4., ...,  2.,  1.,  2.],
       [ 3.,  1.,  1., ...,  1.,  1.,  2.],
       ...,
       [ 5., 10., 10., ..., 10.,  2.,  4.],
       [ 4.,  8.,  6., ...,  6.,  1.,  4.],
       [ 4.,  8.,  8., ...,  4.,  1.,  4.]])

In [21]:
X = cancer_data[:,range(0,9)]
Y = cancer_data[:,9]

In [22]:
cancer_data

array([[ 5.,  1.,  1., ...,  1.,  1.,  2.],
       [ 5.,  4.,  4., ...,  2.,  1.,  2.],
       [ 3.,  1.,  1., ...,  1.,  1.,  2.],
       ...,
       [ 5., 10., 10., ..., 10.,  2.,  4.],
       [ 4.,  8.,  6., ...,  6.,  1.,  4.],
       [ 4.,  8.,  8., ...,  4.,  1.,  4.]])

In [23]:
cancer_data.ndim

2

In [31]:
imp = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=0, copy=True)
X = imp.fit_transform(X) # Imputer(missing_values="NaN", strategy='median', axis=0) = replaced with another line as its getting error
# Imputer is replaced with simple imputer(https://stackoverflow.com/questions/55560740/typeerror-init-got-an-unexpected-keyword-argument-axis)

C:\Users\maham\anaconda3\lib\site-packages\sklearn\impute\_base.py:337: FutureWarning: The 'verbose' parameter was deprecated in version 1.1 and will be removed in 1.3. A warning will always be raised upon the removal of empty columns in the future version.
  warnings.warn(


In [26]:
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=0, copy=True)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)
y_train = y_train.ravel()
y_test = y_test.ravel()

In [33]:
y_train.ndim

1

In [34]:
for K in range(25):
    K_value = K+1
    neigh = KNeighborsClassifier(n_neighbors = K_value)
    neigh.fit(X_train, y_train) 
    y_pred = neigh.predict(X_test)
    print ("Accuracy is ", accuracy_score(y_test,y_pred)*100,"% for K-Value:",K_value)

Accuracy is  94.76190476190476 % for K-Value: 1
Accuracy is  93.80952380952381 % for K-Value: 2
Accuracy is  95.23809523809523 % for K-Value: 3
Accuracy is  95.23809523809523 % for K-Value: 4
Accuracy is  95.23809523809523 % for K-Value: 5
Accuracy is  94.76190476190476 % for K-Value: 6
Accuracy is  94.76190476190476 % for K-Value: 7
Accuracy is  94.28571428571428 % for K-Value: 8
Accuracy is  94.76190476190476 % for K-Value: 9
Accuracy is  94.28571428571428 % for K-Value: 10
Accuracy is  94.28571428571428 % for K-Value: 11
Accuracy is  94.76190476190476 % for K-Value: 12
Accuracy is  94.76190476190476 % for K-Value: 13
Accuracy is  93.80952380952381 % for K-Value: 14
Accuracy is  93.80952380952381 % for K-Value: 15
Accuracy is  93.80952380952381 % for K-Value: 16
Accuracy is  93.80952380952381 % for K-Value: 17
Accuracy is  93.80952380952381 % for K-Value: 18
Accuracy is  93.80952380952381 % for K-Value: 19
Accuracy is  93.80952380952381 % for K-Value: 20
Accuracy is  93.8095238095238